use std::path::PathBuf;

fn main() {
    let root = PathBuf::from("../..");
    let firmware = root.join("firmware");

    println!("cargo:rustc-link-lib=winmm");
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/synth_app.cpp").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/GUI_Paint.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/GUI_Paint.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/synth_c_api.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/hardware.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/gui.cpp").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/gui.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/synthesizer.cpp").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/synthesizer.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/voice.cpp").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/voice.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/midi.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("hal/lcd_1in44.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("hal/lcd_1in44.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("hal/DEV_Config.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("hal/Debug.h").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/Fonts/font12.c").display()
    );
    println!(
        "cargo:rerun-if-changed={}",
        firmware.join("synth_core/Fonts/fonts.h").display()
    );
    println!("cargo:rerun-if-changed=cpp/sim_main.cpp");

    cc::Build::new()
        .cpp(true)
        .std("c++17")
        .include(firmware.join("hal"))
        .include(firmware.join("synth_core"))
        .include(firmware.join("synth_core/Fonts"))
        .file(firmware.join("hal/lcd_1in44.c"))
        .file(firmware.join("synth_core/synth_app.cpp"))
        .file(firmware.join("synth_core/gui.cpp"))
        .file(firmware.join("synth_core/synthesizer.cpp"))
        .file(firmware.join("synth_core/voice.cpp"))
        .file(firmware.join("synth_core/GUI_Paint.c"))
        .file(firmware.join("synth_core/Fonts/font12.c"))
        .file("cpp/sim_main.cpp")
        .compile("synth_core");
}
